### PR TITLE
fix typo in WP_CLI classname

### PR DESCRIPTION
**Pull request by diggy**
`WP_ClI` -> `WP_CLI`

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Hm, no idea why this build is failing.

**Comment by swissspidy** [comment]
Just cleared the cache and restarted the job.

**Comment by schlessera** [comment]
Probably a change in WP `trunk` that is causing an issue...

**Comment by schlessera** [comment]
I can replicate on my local machine with `WP_VERSION=trunk composer behat`. Investigating...

**Comment by schlessera** [comment]
My guess would be that the error string for missing DB credentials changed...

**Comment by swissspidy** [comment]
@schlessera Like this? https://github.com/wp-cli/wp-cli/pull/5094

**Comment by schlessera** [comment]
Maybe this could be the culprit: https://core.trac.wordpress.org/changeset/44827

The issue seems to be that WP-CLI does not recognize the DB failure and does not get to adapt its custom error message. So, instead of the more detailed output that WP-CLI provides, we are now getting the generic Core message:

Image 2019-03-21 at 2 59 37 PM

**Comment by schlessera** [comment]
No, I'm mistaken, the Core is returning a different error case than it should. The test expects a successful connection to the DB server but a failure to select the proper database. However, Core already fails to connect to the DB server here.

**Comment by danielbachhuber** [comment]
@diggy Can you merge `master` to include #136?

**Comment by schlessera** [comment]
Thanks for the PR, @diggy !

**Pull request merged**
